<?php

namespace AppBundle\Repository;

/**
 * DistrictsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictsRepository extends \Doctrine\ORM\EntityRepository
{
}
