<?php

namespace AppBundle\Repository;

/**
 * StreetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetsRepository extends \Doctrine\ORM\EntityRepository
{
}
